export default {
  cities: [
    {
      cityName: "Москва",
      cityLocaltion: [55.755864, 37.617698],
      company: [
        {
          name: "DDX Fitness",
          description: "Фитнес-клуб",
          coordinates: [55.752085, 37.596237],
          address: "​Улица Новый Арбат, 11 ст1​-2 этаж",
          studio: "",
          phone: "+7 (495) 255‒59‒25",
          email: "info@ddxfitness.ru",
          website: "https://ddxfitness.ru",
          rating: "3",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "от 1700 р",
          time: "Открыто до 00:00",
          tags: [
            "Фитнес клуб",
            "Бассейн",
            "Аэробика",
            "Йога",
            "RX-тренировки",
            "ZUMBA",
            "+20 занятий",
          ],
          extra: [
            "Круглосуточный",
            "Только для женщин",
            "Только для мужчин",
            "Детские занятия",
            "Занятия для беременных",
            "Для грудничков",
            "Есть парковка",
            "Душ",
          ],
          cardType: ["gold", "silver", "black"],
          sportType: ["плавание", "бег", "тренажерный зал", "кроссфит"],
        },
        {
          name: "DDX Fitness",
          studio: "small",
          description: "Фитнес-клуб",
          address: "Страстной бульвар, 10 к1",
          coordinates: [55.766106, 37.611482], // Исправляем порядок координат
          phone: "+7 (495) 255‒59‒25",
          email: "info@ddxfitness.ru",
          website: "https://ddxfitness.ru",
          rating: "3.5",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "от 1700 р",
          time: "Открыто до 01:00",
          tags: [
            "Фитнес клуб",
            "Бассейн",
            "Аэробика",
            "Йога",
            "RX-тренировки",
            "ZUMBA",
            "+10 занятий",
          ],
          cardType: ["gold", "silver"],
          sportType: ["бег", "тренажерный зал", "кроссфит"],
        },
        {
          name: "DDX Fitness",
          description: "Фитнес-клуб",
          studio: "",
          address: "​Ходынский бульвар, 4​3 этаж",
          coordinates: [55.784865, 37.531640],
          phone: "+7 (495) 255‒59‒25",
          email: "info@ddxfitness.ru",
          website: "https://ddxfitness.ru",
          rating: "3.8",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "от 1700 р",
          time: "Открыто до 22:00",
          tags: ["Фитнес клуб", "Бассейн", "Аэробика", "Йога", "+20 занятий"],
          cardType: ["gold", "silver", "black"],
          sportType: ["плавание", "бег", "тренажерный зал", "кроссфит"],
        },
        {
          name: "DDX Fitness",
          description: "Фитнес-клуб",
          studio: "small",
          address: "​Улица Маршала Чуйкова, 3",
          coordinates: [55.703885, 37.764986],
          phone: "+7 (495) 255‒59‒25",
          email: "info@ddxfitness.ru",
          website: "https://ddxfitness.ru",
          rating: "4",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "от 1700 р",
          time: "Открыто до 23:00",
          tags: [
            "Фитнес клуб",
            "Бассейн",
            "Аэробика",
            "Йога",
            "RX-тренировки",
            "ZUMBA",
            "+30 занятий",
          ],
          cardType: ["gold"],
          sportType: ["тренажерный зал"],
        },
        {
          name: "Xfit",
          description: "Фитнес-клуб",
          studio: "small",
          address: "​Улица Правды, 21 ст2",
          coordinates: [55.788044, 37.579538],
          phone: "+7 (495) 432‒53‒09",
          email: "pvd-manager@xfit.ru",
          website: "pravda.xfit.ru",
          rating: "5",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "от 1700 р",
          time: "Открыто до 01:00",
          tags: [
            "Фитнес клуб",
            "Бассейн",
            "Аэробика",
            "Йога",
            "RX-тренировки",
            "ZUMBA",
            "+20 занятий",
          ],
          cardType: ["gold", "silver", "black"],
          sportType: ["плавание", "бег", "тренажерный зал", "кроссфит"],
        },
        {
          name: "Xfit",
          description: "Фитнес-клуб",
          studio: "",
          address: "Ленинградский проспект, 31а ст1",
          coordinates: [55.783600, 37.560197],
          phone: "+7 (495) 172‒39‒47",
          email: "monsport-manager@xfit.ru",
          website: "https://monarh.xfit.ru",
          rating: "4.5",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "от 1700 р",
          time: "Открыто до 01:00",
          tags: [
            "Фитнес клуб",
            "Бассейн",
            "Аэробика",
            "Йога",
            "RX-тренировки",
            "ZUMBA",
            "+50 занятий",
          ],
          cardType: ["gold", "silver", "black"],
          sportType: ["плавание", "бег", "тренажерный зал", "кроссфит"],
        },
        {
          name: "Xfit",
          description: "Фитнес-клуб",
          studio: "small",
          address: "Смоленская улица, 8",
          coordinates: [55.746274, 37.580391], // Исправляем порядок координат
          phone: "+7 (495) 859‒45‒57",
          email: "smolenskaya@xfit.su",
          website: "www.xfit.ru",
          rating: "1.5",
          logo: "/img/ddx.png",
          marker: "/img/marker.png",
          price: "",
          time: "Открыто до 01:00",
          tags: [
            "Фитнес клуб",
            "Бассейн",
            "Аэробика",
            "Йога",
            "RX-тренировки",
            "ZUMBA",
            "+10 занятий",
          ],
          cardType: ["gold"],
          sportType: ["тренажерный зал"],
        },
      ],
    },
    {
      cityName: "Санкт-Петербург",
      cityLocaltion: [59.938784, 30.314997],
      company: [],
    },
  ],
};
