export default {
    company: [
        {
            name: "DDX Fitness",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: '​Улица Новый Арбат, 11 ст1​-2 этаж',
            coordinates: [37.6176, 55.7558],
            phone: '+7 (495) 255‒59‒25',
            email: 'info@ddxfitness.ru',
            website: 'https://ddxfitness.ru',
        },
        {
            name: "DDX Fitness",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: 'Страстной бульвар, 10 к1',
            coordinates: [55.766106, 37.611482],
            phone: '+7 (495) 255‒59‒25',
            email: 'info@ddxfitness.ru',
            website: 'https://ddxfitness.ru',
        },
        {
            name: "DDX Fitness",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: '​Ходынский бульвар, 4​3 этаж',
            coordinates: [55.784865, 37.531640],
            phone: '+7 (495) 255‒59‒25',
            email: 'info@ddxfitness.ru',
            website: 'https://ddxfitness.ru',
        },
        {
            name: "DDX Fitness",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: '​Улица Маршала Чуйкова, 3',
            coordinates: [55.703885, 37.764986],
            phone: '+7 (495) 255‒59‒25',
            email: 'info@ddxfitness.ru',
            website: 'https://ddxfitness.ru',
        },
        {
            name: "Xfit",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: '​Улица Правды, 21 ст2',
            coordinates: [55.788044, 37.579538],
            phone: '+7 (495) 432‒53‒09',
            email: 'pvd-manager@xfit.ru',
            website: 'pravda.xfit.ru',
        },
        {
            name: "Xfit",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: 'Ленинградский проспект, 31а ст1',
            coordinates: [55.783600, 37.560197],
            phone: '+7 (495) 172‒39‒47',
            email: 'monsport-manager@xfit.ru',
            website: 'https://monarh.xfit.ru',
        },
        {
            name: "Xfit",
            description: 'Фитнес-клуб',
            city: 'Москва',
            address: 'Смоленская улица, 8',
            coordinates: [55.746274, 37.580391],
            phone: '+7 (495) 859‒45‒57',
            email: 'smolenskaya@xfit.su',
            website: 'www.xfit.ru',
        }
    ]
}
